### ISSUE TITLE
Script for Call Graph Generation

### ISSUE THREAD

**Issue by papachristoumarios** [mturquette/mturquette.github.com#1]
Hello mturquette,

I was reading your article regarding the generation of the Linux Call Graph using `egypt`. There was not a comments section so I decided to post my addition as an issue. It would be better for the reader if you included a comprehensive UNIX script to generate the call graph for you.
One that came to my mind is:
```bash
#!/bin/bash

find . -type f -name '*.expand' | xargs -n $(find . -type f -name '*.expand' | wc -l) egypt
```

Which can be used either to generate the text representation:

```
./callgraph.sh > graph.txt
```

For exporting the .svg: 

```
./callgraph.sh | dot -Grankdir=LR -Tsvg -o callgraph.svg
```

Hope you'll like it (and add it to the blog post),
Kind regards,
Marios

**Comment by mturquette** [comment]
Thanks a lot Mario! I'll update the article and attribute the change to you.
